version: "3"
services:
  news-service:
    image: golang:1.18
    restart: on-failure:5
    volumes:
     - ./:/backend
    working_dir: /backend
    command:
     - /bin/bash
     - -c
     - go run ./cmd/main.go
    ports:
     - "3000:3000/tcp"
    environment:
      - PG_USER=admin
      - PG_PASS=admin
      - PG_HOST=library-postgres
      - PG_PORT=5432
      - PG_DB=librarydb
      - PORT=3000
      - JWTSECRET="The universe has a beginning, but it has no end. —Infinite.\nStars too have a beginning, but are by their own power destroyed. —Finite.\nHistory teaches us that those who hold wisdom are often the most foolish.\nThe fish in the sea know not the land. If they too hold wisdom, they too will be destroyed.\nIt is more ridiculous for Man to exceed light speed than for fish to live ashore.\nThis may also be called God's final ultimatum to those who rebel."
    networks: 
      default:
        aliases: 
          - library-service
    depends_on:
      - library-postgres
  adminer:
    image: adminer:4-standalone
    restart: on-failure:5
    ports:
      - "3001:8080/tcp"
    environment:
      - "ADMINER_DEFAULT_SERVER=library-postgres"
    networks:
      default:
        aliases:
          - adminer2
  news-postgres:
    image: postgres:14-alpine
    restart: on-failure:5
    volumes:
      - ./pgsql:/var/lib/postgresql
    ports:
      - "3002:5432/tcp"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=librarydb
      - PGPORT=5432
    networks:
      default:
        aliases:
          - library-postgres
networks:
  default:
